### ISSUE TITLE
PostgreSQLのコンテナ利用化

### ISSUE THREAD

**Issue by ds-hack** [ds-hack/data-infrastracture#1]
ローカル開発環境としてminikubeをインストール。

DBの認証情報は`dshack-secret.yaml`に記載し、リポジトリ管理対象外とする。

 - dshack-secret.yamlの雛形
```
apiVersion: v1
kind: Secret
metadata:
  namespace: dshack-development
  name: postgres-secret
type: Opaque
data:
  dbname: xxxxxxx
  username: xxxxxxx
  password: xxxxxxx
  testdbname: xxxxxxx
```
xxxxxxの中身は、base64エンコード後の値を入れる必要がある。`dshack`をDB名にしたい場合は、xxxxxxには`ZHNoYWNr`を入力する。
```
% echo -n "dshack" | base64 -
ZHNoYWNr
```

- DBコンテナの起動

下記コマンドを叩くと2つのPodが立ち上がり、それぞれ開発用・テスト用DBである。（デプロイはまだまだ先の話なので本番用DBは未作成）
```
kubectl apply -f dshack-secret.yaml
kubectl apply -f dshack-development.yaml
```

開発時はホストPCのSQLクライアントからDBに接続出来た方が色々と便利なので、Headless Service(kubernetesクラスタ内でPod名でIPアドレスを解決できるサービス)とは別にNodePort Serviceを作成している。

NodeのIPアドレスはminikubeの場合、`minikube ip`コマンドで確認でき、portはyaml内で30010(開発用DB)・30011(テスト用DB)に設定している。

DB接続情報は下記の通り
```
host: minikube ipで表示されるIPアドレス
port: 30010(開発用DB)&30011(テスト用DB)
username: dshack-secret.yamlの値
password: dshack-secret.yamlの値
dbname: dshack-secret.yamlの値
```
