### ISSUE TITLE
ユニットテスト自動化

### ISSUE THREAD

**Issue by ds-hack** [ds-hack/data-infrastracture#5]
~~運用コストの低いCircle CIを採用する~~

Skaffoldを利用してLocalのソースコード変更時にk8s上での自動テスト（ビルド）を実施する。

https://github.com/GoogleContainerTools/skaffold/tree/master/examples

クラウド上での運用を行う際には、**Github Webhook + Google Cloud Build**などの組み合わせでCI/CDを実現する

### Document

https://skaffold.dev/docs/

### インストール

macの場合、brewによりインストールできる。
```
brew install skaffold
```

Skaffoldの設定はリポジトリ直下の`skaffold.yaml`ファイルに書く。
```
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: data-infrastructure
build:
  artifacts:
  - image: dshacks/pytest-job
deploy:
  kubectl:
    manifests:
    - dshack-development.yaml
    - dshack-secret.yaml
```

### 主な利用法

`skaffold dev`コマンドを実行すると、`skaffold.yaml`に従って

1. Dockerfileによるイメージファイルのビルド
2. ビルドイメージのtag付け
3. 上記イメージを利用するk8s manifestファイルの更新
4. `kubectl apply -f`コマンドによるk8s manifestのデプロイ
5. podログのストリーミング

が自動的に行われる。

上記がソースコードを保存する度に自動的に実施されるので、任意のタイミングで最新状態のコンテナログを確認することができる。

ユニットテストの実行コマンドをDockerfileに記載し、k8s manifestに定義することでユニットテストの自動化が可能。

`Ctrl + C`でキャンセルすると`kubectl delete -f`コマンドにより、自動的に全てのResource, Service etcを終了してくれるので、自分でそれらを削除する必要はない。
